# Basic introduction to tensors and tensor handling

In [ ]:
pip install torch

Defaulting to user installation because normal site-packages is not writeable
     |████████████████▏               | 37.1 MB 22.6 MB/s eta 0:00:02

In [20]:
import torch

#Create a 1D tensor called a , create a python list and cast it using the tensor constructor
a= torch.tensor([7, 4, 3, 2, 6])

#As with list we can access the elements with an int and square bracket
print(a[:5]) # First 5 elements
print(a) #Print the entire tensor

#Use item() method to convert each tensor element to a Python scalar
for element in a:
    print(element.item(), end=' ')
print()

tensor([7, 4, 3, 2, 6])
tensor([7, 4, 3, 2, 6])
7 4 3 2 6 


In [50]:
#Use the data attribute dtype to find the type of data stored in the tensor
a = torch.tensor([0, 1, 2, 3, 4])
print("Integer tensor:")
print(a.dtype)
print(a.type())

a = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
print("\nFloat tensor:")
print(a.dtype)
print(a.type())

#Specify the data type of a tensor in the constructor using the parameter dtype
#Effectively a data type override
a = torch.tensor([0, 1, 2, 3, 4], dtype=torch.int32)  # Use integers, not floats
print("\nOverride to int32:")
print(a.dtype)

#Using the FloatTensor method to create a float tensor explicitly
a=torch.FloatTensor([0, 1, 2, 3, 4])
print("\nUsing FloatTensor Method:")
print(a.type())
print(a)

#Convert the tensor type using methods
a=torch.tensor([0,1,2,3,4]) #Tensor of long type
a=a.type(torch.FloatTensor) #Convert to Float using the type method w argument torch.FloatTensor
print("\nType converted from long to float using type():")
print(a.type())


Integer tensor:
torch.int64
torch.LongTensor

Float tensor:
torch.float32
torch.FloatTensor

Override to int32:
torch.int32

Using FloatTensor Method:
torch.FloatTensor
tensor([0., 1., 2., 3., 4.])

Type converted from long to float using type():
torch.FloatTensor


In [64]:
#Exploring tensor attributes

#Use size method to return number of elements in a tensor
a = torch.Tensor([0, 1, 2, 3, 4])
print(a.size())

# Determining tensor dimension or rank using ndimension()
print("\nNumDimensions:")
print(a.ndimension())

#Converting 1D tensors to 2D tensors
a = torch.Tensor([1, 2, 3, 4, 5]) 
a_col = a.view(5, 1)  # Convert to 2D tensor using View method, 5 rows 1 col
print("\nOriginal 1D tensor:")
print(a)
print("\nConverted to 2D (5x1):")
print(a_col)

torch.Size([5])

NumDimensions:
1

Original 1D tensor:
tensor([1., 2., 3., 4., 5.])

Converted to 2D (5x1):
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])


In [72]:
#Pytorch tensors can be interconverted to NumPy arrays and vice versa
import numpy as np
import pandas as pd

np_array= np.array([0.0, 1.0, 2.0, 3.0, 4.0])

#convert np array to torch_tensor
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
#convert torch_tensor back to np array
np_array_again = torch_tensor.numpy()
print(np_array_again)

pandas_series=pd.Series([0.1, 2, 0.3, 10.1])
#Pandas to torch
pandas_to_torch=torch.from_numpy(pandas_series.values)
print(pandas_to_torch)

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)
[0. 1. 2. 3. 4.]
tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)


In [78]:
#Indexing and slicing methods to access a value or set of values in a tensor

c=torch.tensor([20, 1, 2, 3, 4])
print(c[0])

#Change the fifth element of the tensor from 4 to 0
c[4]=0
print(c)

#select elements at index 1 to 4 in tensor c to new torch tensor d, not counting element at last index
print("\nNew tensor d is:")
d = c[1:4] #assign the 2nd and
print(d)

tensor(20)
tensor([20,  1,  2,  3,  0])

New tensor d is:
tensor([1, 2, 3])
