Text data requires preprocessing (tokenization and padding).  We can use TensorFlow's TextVectorization l ayer to convert text data into numerical format for model training.

In [3]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='urllib3')

from tensorflow.keras.layers import TextVectorization

#Sample text data
texts = [
    "Hello, how are you?",
    "I am fine, thank you!",
    "How about you?",
    "I am good too."
]

#Create the TextVectorization layer top tokenize and pad text sequences
vectorizer = TextVectorization(output_mode='int', max_tokens=100, output_sequence_length=10)

#Adapt the vectorizer to the text data
vectorizer.adapt(texts)

#Transform the text into numerical format
text_vectorized = vectorizer(texts)
print("Vectorized text data is:\n", text_vectorized.numpy())

Vectorized text data is:
 [[ 8  4 11  2  0  0  0  0  0  0]
 [ 3  5 10  7  2  0  0  0  0  0]
 [ 4 12  2  0  0  0  0  0  0  0]
 [ 3  5  9  6  0  0  0  0  0  0]]
